### ISSUE TITLE
Ubuntu 18.04 (bionic) ldc-1.8.0 behind windows/mac versions ldc-1.24.0

### ISSUE THREAD

**Issue by kmturley** [ldc-developers/ldc#3633]
Github runners currently support:

- Windows Server 2019 | windows-latest or windows-2019
- Ubuntu 20.04 | ubuntu-20.04
- Ubuntu 18.04 | ubuntu-latest or ubuntu-18.04
- Ubuntu 16.04 | ubuntu-16.04
- macOS Big Sur 11.0 | macos-11.0
- macOS Catalina 10.15 | macos-latest or macos-10.15

https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources

If I run a GitHub Action with the following code:
```
name: Release

on:
  workflow_dispatch:

jobs:
  build_release:
    name: Build release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: linux
          - os: macos-latest
            name: mac
          - os: windows-latest
            name: win
    steps:
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install ldc

      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: brew install ldc

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: choco install ldc 

      - name: Debug
        shell: bash
        run: ldc2 --version
```

The output is shown as:
```
ubuntu-latest = LDC - the LLVM D compiler (1.8.0)
macos-latest = LDC - the LLVM D compiler (1.24.0)
windows-latest = LDC - the LLVM D compiler (1.24.0)
```

Can we get higher than v1.8.0 on Ubuntu Bionic?
https://packages.ubuntu.com/bionic/ldc

I know that it works, because you can install it manually using:
```
sudo apt-get update && sudo apt-get -yq install libx11-dev
curl -fsS https://dlang.org/install.sh | bash -s ldc
~/dlang/install.sh install ldc-1.17.0,dub
source ~/dlang/ldc-1.17.0/activate
```

LDC compiler is used for many audio plugin libraries, and getting plugins built cross-platform is currently a painpoint:
https://github.com/AuburnSounds/Dplug/blob/master/azure-pipelines.yml

Thanks!
